version: '3.8'

services:
  mongo:
    image: mongo:4.2
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - '8080:8080'
    depends_on:
      - backend

volumes:
  mongo-data:
